# Simple Makefile
CC = g++ -Wall

# compile file names Rating.cpp Person.cpp Matcher.cpp main.cpp
all: Rating.cpp Person.cpp Matcher.cpp main.cpp
	${CC} Rating.cpp Person.cpp Matcher.cpp main.cpp

clean:
	rm *.o